name: Build & Deploy

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Prounity site
        uses: appleboy/ssh-action@master
        with:
          scope: "Ibrokhim1006"

          script: |
            cd /var/www/html/ui
            rm -rf ui
            git clone https://github.com/prounitycompany/ui.git
